server:
  port: 8087
spring:
  application:
    name: yls_server_zuul

  ##注册服务，微服务架构
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${server.port}
##配置服务网关
zuul:
  ##配置路由拦截
  routes:
    ribbon:
      path: /ribbon/**
      ##转发到消费者
      serviceId: yls-server-consumer

    fegin:
      path: /feign/**
      ##转发到消费者
      serviceId: yls-server-consumer
  ##为每个服务加前缀
  prefix: /v1